// <auto-generated />
using System;
using GetPriceUrl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetPriceUrl.Migrations
{
    [DbContext(typeof(LaptopPriceDbContext))]
    [Migration("20231030084410_AddPriceToLaptopURL")]
    partial class AddPriceToLaptopURL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GetPriceUrl.Infrastructure.Models.LaptopURL", b =>
                {
                    b.Property<int>("LaptopURLID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaptopURLID"));

                    b.Property<int?>("LaptopID")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("LaptopURLID");

                    b.ToTable("LaptopURL");
                });
#pragma warning restore 612, 618
        }
    }
}
